### ISSUE TITLE
API key request

### ISSUE THREAD

**Issue by whippingdot** [replit/replit-vscode#18]
Can I use this extension. I am a coder on repl.it, and in the API website it says that you have to ask in the discord for permission, but I don't have discord so I am asking here. I know this is only for developers but it would be really handy for me too as I am doing projects with replers on a repl and I really want to use vscode for spell check and prettier.

**Comment by masad-frost** [comment]
This project is still in an exploratory phase. @Scoder12 (who is a community members) and I built it in a couple of days to explore what it would be like to use other IDEs with repl.it. Currently we only allow very close and trusted community members to use this API as we iron out the kinks and lockdown our infrastructure against abuse.

What is your repl.it account? I'll reach out in an email.

**Comment by masad-frost** [comment]
For future readers, if you have a hacker plan subscription, please leave your repl.it username and I'll reach out to you. It's easier for us to trust people with hacker plan and hold them liable for abuse.

**Comment by whippingdot** [comment]
Umm I have hacker plan and my username is Whippingdot. I don't want to be held for abuse so what do you mean by abuse of this extension??

**Comment by whippingdot** [comment]
@masad-frost

**Comment by masad-frost** [comment]
Meaning malicious activity, like mining crypto for example or DDOS attacks.

**Comment by whippingdot** [comment]
Ok, thanks. Also, I don't even know what a mining crypto is. I think I know what a DDOS attack is as I searched it up when repl was acting slow and people were saying it was a DDOS attack...

**Comment by whippingdot** [comment]
Not to rush or anything but 2 days have passed... 👀

**Comment by Scoder12** [comment]
@whippingdot did you get the email so we can close this? 
For future readers: the best place to ask for API access is in the [repl.it discord](https://repl.it/discord)

**Comment by whippingdot** [comment]
I don't have discord, sorry, and no, I didn't get the email. 😢

**Comment by masad-frost** [comment]
Hey @whippingdot, you can get your token from here https://protodoc.turbio.repl.co/ click the link where it says `looking for a token?`

**Comment by whippingdot** [comment]
@masad-frost it doesn't work
![image](https://user-images.githubusercontent.com/64354499/105936870-76c79500-607a-11eb-82c3-d5bfd3da803f.png)

**Comment by whippingdot** [comment]
~~open this again please as it still doesn't work @masad-frost~~
